### ISSUE TITLE
taglist和函数搜索都无法跳转

### ISSUE THREAD

**Issue by sunshiyong85** [kurli/CodeNavigator#2]
●现象发生时动画
[CodeNavigator_bug.zip](https://github.com/kurli/CodeNavigator/files/1486395/CodeNavigator_bug.zip)

●现象
taglist和函数搜索都无法跳转
详细参考附件视屏

●问题内容
经过测试发现，无法跳转发生在文件内的行跳转
taglist：因为是同一文件，所以无法跳转
函数搜索：a文件中搜索func函数，可以跳转转func所在文件的b文件，但是无法跳转到b文件func函数所在的行数，只能跳转到b文件的第一行

●问题手机
A1586
IOS：11.1.2(15B202)

●其他
1.IOS升级前 IOS 10.x.x没有问题
2.ios升级后，删除APP后重新再安装，问题一样发生

**Comment by kurli** [comment]
@sunshiyong85 您好，Pad版也有同样的问题，都是iOS升级到11后导致的

Pad上的已经修复，Phone版的遇到其他UI的问题，正在找时间适配，敬请谅解  :-)

**Comment by sunshiyong85** [comment]
谢谢回复，期待您尽快解决问题

**Comment by sunshiyong85** [comment]
@kurli 您好，请问iphone何时能更新？地铁上没这个软件不习惯了

**Comment by kurli** [comment]
@sunshiyong85  已更新，谢谢  :-)
